### PR TITLE
Interface improvements

### PR DESCRIPTION
**Pull request by artegoser**
New style

image
image

Fixed search input isssue

image
image

### CODE REVIEW

**Comment by artegoser** [comment]
image

**Comment by DarkCat09** [comment]
TODO: add animation to switch on main page and figure out why it isn't initially checked despite `checked="checked"`

**Comment by DarkCat09** [comment]
@artegoser, have a look, please. Would you approve this redesign?

**Comment by DarkCat09** [comment]
Do not merge yet

**Pull request merged**
